[package]
cjc-version = "0.55.3"
name = "maa"
description = "Cangjie language binding for MaaFramework"
version = "0.1.0"
compile-option = ""
link-option = ""
output-type = "static"
src-dir = "src"
target-dir = "build"
package-configuration = {}

[dependencies]
