[package]
cjc-version = "1.0.5"
name = "maa"
description = "Cangjie language binding for MaaFramework"
version = "0.1.0"
compile-option = "-Woff unused"
link-option = "-L ./deps/lib -l MaaFramework -l MaaToolkit"
output-type = "static"
src-dir = "src"
target-dir = "build"
package-configuration = {}

[dependencies]
